name: Node.js CI

on: [push]

jobs:
  build-fe:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: pinhask/notification-fe
        context: .  
        tags: pinhask/notification-fe:${{ steps.extract_branch.outputs.branch }}
        file: app/Dockerfile
      env:
        CI: true
  build-be:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: pinhask/notification-be:${{ steps.extract_branch.outputs.branch }}
        context: .
      env:
        CI: true